---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    openssh:
      server:
        password_authentication: "yes"

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: debian-8.1

suites:
  - name: default
    run_list:
      - recipe[ut_base]
